### PR TITLE
feat(konflux): update buildah to support subscriptions

### PR DESCRIPTION
**Pull request by vkrizan**
## Secure Coding Practices Checklist GitHub Link
    - https://github.com/RedHatInsights/secure-coding-checklist

    ## Secure Coding Checklist
    - [ ] Input Validation
    - [ ] Output Encoding
    - [ ] Authentication and Password Management
    - [ ] Session Management
    - [ ] Access Control
    - [ ] Cryptographic Practices
    - [ ] Error Handling and Logging
    - [ ] Data Protection
    - [ ] Communication Security
    - [ ] System Configuration
    - [ ] Database Security
    - [ ] File Management
    - [ ] Memory Management
    - [ ] General Coding Practices

### CODE REVIEW

**Comment by vkrizan** [comment]
@skateman

**Review by skateman — APPROVED** [review]

**Comment by skateman** [comment]
You don't need this as https://github.com/RedHatInsights/remediations-consumer/pull/330 makes it obsolete.

**Comment by vkrizan** [comment]
Superseded by #330

**Pull request closed without merging**
